#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linq2sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Adresar")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFizickaLica(FizickaLica instance);
    partial void UpdateFizickaLica(FizickaLica instance);
    partial void DeleteFizickaLica(FizickaLica instance);
    partial void InsertZaposleni(Zaposleni instance);
    partial void UpdateZaposleni(Zaposleni instance);
    partial void DeleteZaposleni(Zaposleni instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::linq2sql.Properties.Settings.Default.AdresarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FizickaLica> FizickaLicas
		{
			get
			{
				return this.GetTable<FizickaLica>();
			}
		}
		
		public System.Data.Linq.Table<Zaposleni> Zaposlenis
		{
			get
			{
				return this.GetTable<Zaposleni>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FizickaLica")]
	public partial class FizickaLica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFizickoLice;
		
		private string _Ime;
		
		private string _Prezime;
		
		private string _Adresa;
		
		private string _Telefon;
		
		private EntitySet<Zaposleni> _Zaposlenis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFizickoLiceChanging(int value);
    partial void OnIdFizickoLiceChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public FizickaLica()
		{
			this._Zaposlenis = new EntitySet<Zaposleni>(new Action<Zaposleni>(this.attach_Zaposlenis), new Action<Zaposleni>(this.detach_Zaposlenis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFizickoLice", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFizickoLice
		{
			get
			{
				return this._IdFizickoLice;
			}
			set
			{
				if ((this._IdFizickoLice != value))
				{
					this.OnIdFizickoLiceChanging(value);
					this.SendPropertyChanging();
					this._IdFizickoLice = value;
					this.SendPropertyChanged("IdFizickoLice");
					this.OnIdFizickoLiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="NVarChar(250)")]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FizickaLica_Zaposleni", Storage="_Zaposlenis", ThisKey="IdFizickoLice", OtherKey="idFizickoLice")]
		public EntitySet<Zaposleni> Zaposlenis
		{
			get
			{
				return this._Zaposlenis;
			}
			set
			{
				this._Zaposlenis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zaposlenis(Zaposleni entity)
		{
			this.SendPropertyChanging();
			entity.FizickaLica = this;
		}
		
		private void detach_Zaposlenis(Zaposleni entity)
		{
			this.SendPropertyChanging();
			entity.FizickaLica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zaposleni")]
	public partial class Zaposleni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdZaposleni;
		
		private int _idFizickoLice;
		
		private System.Nullable<int> _GodinaStaza;
		
		private EntityRef<FizickaLica> _FizickaLica;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdZaposleniChanging(int value);
    partial void OnIdZaposleniChanged();
    partial void OnidFizickoLiceChanging(int value);
    partial void OnidFizickoLiceChanged();
    partial void OnGodinaStazaChanging(System.Nullable<int> value);
    partial void OnGodinaStazaChanged();
    #endregion
		
		public Zaposleni()
		{
			this._FizickaLica = default(EntityRef<FizickaLica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdZaposleni", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdZaposleni
		{
			get
			{
				return this._IdZaposleni;
			}
			set
			{
				if ((this._IdZaposleni != value))
				{
					this.OnIdZaposleniChanging(value);
					this.SendPropertyChanging();
					this._IdZaposleni = value;
					this.SendPropertyChanged("IdZaposleni");
					this.OnIdZaposleniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFizickoLice", DbType="Int NOT NULL")]
		public int idFizickoLice
		{
			get
			{
				return this._idFizickoLice;
			}
			set
			{
				if ((this._idFizickoLice != value))
				{
					if (this._FizickaLica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidFizickoLiceChanging(value);
					this.SendPropertyChanging();
					this._idFizickoLice = value;
					this.SendPropertyChanged("idFizickoLice");
					this.OnidFizickoLiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GodinaStaza", DbType="Int")]
		public System.Nullable<int> GodinaStaza
		{
			get
			{
				return this._GodinaStaza;
			}
			set
			{
				if ((this._GodinaStaza != value))
				{
					this.OnGodinaStazaChanging(value);
					this.SendPropertyChanging();
					this._GodinaStaza = value;
					this.SendPropertyChanged("GodinaStaza");
					this.OnGodinaStazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FizickaLica_Zaposleni", Storage="_FizickaLica", ThisKey="idFizickoLice", OtherKey="IdFizickoLice", IsForeignKey=true)]
		public FizickaLica FizickaLica
		{
			get
			{
				return this._FizickaLica.Entity;
			}
			set
			{
				FizickaLica previousValue = this._FizickaLica.Entity;
				if (((previousValue != value) 
							|| (this._FizickaLica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FizickaLica.Entity = null;
						previousValue.Zaposlenis.Remove(this);
					}
					this._FizickaLica.Entity = value;
					if ((value != null))
					{
						value.Zaposlenis.Add(this);
						this._idFizickoLice = value.IdFizickoLice;
					}
					else
					{
						this._idFizickoLice = default(int);
					}
					this.SendPropertyChanged("FizickaLica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
